# Generated by Django 5.1.7 on 2025-03-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=100)),
                ('is_canceled', models.IntegerField()),
                ('lead_time', models.IntegerField()),
                ('arrival_date_year', models.IntegerField()),
                ('arrival_date_month', models.CharField(max_length=20)),
                ('arrival_date_week_number', models.IntegerField()),
                ('arrival_date_day_of_month', models.IntegerField()),
                ('stays_in_weekend_nights', models.IntegerField()),
                ('stays_in_week_nights', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('babies', models.IntegerField()),
                ('meal', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('market_segment', models.CharField(max_length=50)),
                ('distribution_channel', models.CharField(max_length=50)),
                ('is_repeated_guest', models.IntegerField()),
                ('previous_cancellations', models.IntegerField()),
                ('previous_bookings_not_canceled', models.IntegerField()),
                ('reserved_room_type', models.CharField(max_length=10)),
                ('assigned_room_type', models.CharField(max_length=10)),
                ('booking_changes', models.IntegerField()),
                ('deposit_type', models.CharField(max_length=50)),
                ('agent', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('days_in_waiting_list', models.IntegerField()),
                ('customer_type', models.CharField(max_length=50)),
                ('adr', models.FloatField(blank=True, null=True)),
                ('required_car_parking_spaces', models.IntegerField()),
                ('total_of_special_requests', models.IntegerField()),
                ('reservation_status', models.CharField(max_length=50)),
                ('reservation_status_date', models.DateField()),
            ],
        ),
    ]
